name: workflow
on:  
  push:
    branches:
      - main   

jobs: 
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Install dependencies
        run: make setup

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint